# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d519372dffda596d194a8858ceaac0f6b3cbbb1aaf1268fc58d1db78e7b11cf87766abcc71235a0beb5f154bbd8d4caf40ef9f0e269e46aa0f69b801b2603bd8

test:
  secret_key_base: 2806f82a1fb62ed0a107a6a862cee34da67f5aa5180e01ebacc87491041e19467b31dc2b1da1b6f5968c170f81b74a1efed5797e5f48c17141e9cecd4d74d35e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
